[package]
name = "wgpu_bitonic_sort"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.16.0", features = ["derive"] }
wgpu = "0.20.0"

[dev-dependencies]
rand = { version = "0.8.5", features = ["small_rng"] }
tokio = { version = "1.37.0", features = ["full"] }
