[package]
name = "audio_video"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
bevy_math = "0.15.3"
color = "0.2.3"
cpal = "0.15.3"
image = "0.25.6"
rustfft = "6.2.0"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
